file_format: "1"
id: automaton169
name: Automaton169
type: shield
url: https://github.com/mowam/automaton169/
requires: [seeeduino_xiao_ble]
features:
  - keys
  - underglow
siblings:
  - automaton169_left
  - automaton169_right
