manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: crides
      url-base: https://github.com/crides
  projects:
    - name: zmk
      remote: crides
      revision: led-widgets
      import: app/west.yml
  self:
    path: config
